[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install", "cd server && npm install", "cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "node server/db-init.js && NODE_ENV=production node server/index.js"
